### ISSUE TITLE
Support cross-mod require introduced in 0.17

### ISSUE THREAD

**Issue by RustyBlade64** [KirkMcDonald/FactorioLoaderLib#6]
0.17 introduces the possibility to `require()` files from other mods. From the [preliminary modding changelog](https://forums.factorio.com/61239):
> * Lua scripts can now use `require("__mod-name__.file")` syntax.

When mods start using this feature, LoaderLib will eventually need to support this as well.

**Comment by KirkMcDonald** [comment]
This change should be relatively straightforward, but will require some top-level reorganization of the mod-loading types. At the moment, the code assumes that a given mod will be loaded once and discarded. This change will require keeping a top-level registry of all mod-loaders, and adding a new loader which can identify script names of this form and forward them to the appropriate mod loader.

**Comment by clarfonthey** [comment]
I'm running into this now trying to get the calculator working with seablock -- the mods are using `__base__` to reference the base mod but this isn't being loaded at the correct path. Would be willing to help implement this, although not really sure where I should start.
